os:
- linux
- osx

language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
    - php: 5.3
    - php: 5.3.3
    - php: 7.0

notifications:
  email: false
